version: "3"

services:
  api1:  
    ports:
      - 80:80
    build:
      context: api1
      dockerfile: Dockerfile
  api2:
    environment:
      - PORT=8080
      - API1_HOST=http://localhost:5000
    ports:
      - 8080:8080
    build:
      context: api2
      dockerfile: Dockerfile
