version: "3"

services:
  api1:
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: api1
      dockerfile: Dockerfile
  api2:
    environment:
      - PORT=3333
      - API1_HOST=http://localhost:5000
    ports:
      - 3333:3333
    build:
      context: api2
      dockerfile: Dockerfile
