# This is a basic workflow to help you get started with Actions

name: Run .Net tests in api1

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '5.0.x'
      - run: dotnet restore api1
      - run: dotnet build api1
      - run: dotnet test api1
