name: Deploy containers to heroku

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy api1 to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: outrowender@gmail.com
        heroku_api_key: ${{ secrets.heroku_api_key }}
        heroku_app_name: outrowender-ingaia-api1
        dockerfile_directory: api1/
        
    - name: Deploy api2 to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: outrowender@gmail.com
        heroku_api_key: ${{ secrets.heroku_api_key }}
        heroku_app_name: outrowender-ingaia-api2
        dockerfile_directory: api2/
