name: Build, test and deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: build and test api1
      uses: actions/setup-dotnet@v1.8.0
      with:
          dotnet-version: 5.0.x
    - name: install dependencies api1
      run: dotnet restore api1
    - name: build api1
      run: dotnet build api1
    - name: test api1
      run: dotnet test api1 --no-restore --verbosity normal
      
    - name: build and test api2
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14
    - name: install dependencies api2
      run: cd api2 && npm install
    - name: test api2
      run: cd api2 && npm run test
      
    - name: deploy api1
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: outrowender@gmail.com
        heroku_api_key: ${{ secrets.heroku_api_key }}
        heroku_app_name: outrowender-ingaia-api1
        dockerfile_directory: api1/
        
    - name: deploy api2
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: outrowender@gmail.com
        heroku_api_key: ${{ secrets.heroku_api_key }}
        heroku_app_name: outrowender-ingaia-api2
        dockerfile_directory: api2/
